<?php
/**
 * layout-white:/html.phtml
 *
 * @creation  2016-11-22
 * @version   1.0
 * @package   layout-white
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

/** Used class.
 *
 */

/* @var $app    \OP\UNIT\App */
/* @var $content string      */
?>
<!doctype html>
<html lang="<?= $app->Env()->Lang() ?>">
	<head>
		<?= $app->Template('layout/head.phtml') ?>
	</head>
	<body id="body" class="body">
		<div id="head-area">
			<?= $app->Template('layout/header.phtml') ?>
			<?= $app->Template('layout/menu/top.phtml') ?>
		</div>
		<div id="body-area">
			<div>
				<!-- left menu -->
				<?= $app->Template('layout/menu/left.phtml') ?>
			</div>
			<div id="content-area" class="content-area">
				<?= $content ?>
			</div>
			<div>
				<!-- right menu -->
				<?= $app->Template('layout/menu/right.phtml') ?>
			</div>
		</div>
		<div id="foot-area">
			<?= $app->Template('layout/menu/bottom.phtml') ?>
			<?= $app->Template('layout/footer.phtml') ?>
		</div>
	</body>
</html>
